#%RAML 1.0 Trait
---
headers: 
  transaction-id:
    displayName: Transaction Id
    description: Transaction Id of calling Application
    type: string
    required: true
    example: XTRTRDF
  Content-type:
    type: string
    required: true
    example:
      "application/json"